# see: https://zenn.dev/hkusu/articles/9b0255084f4cba
name: Approve Me
on:
  issue_comment:
    types: [created, edited]
jobs:
  approve:
    name: Approve
    if: |
      github.event.issue.state == 'open' &&
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '@github-actions approve me') &&
      (github.event.action != 'edited' || (github.event.action == 'edited' && !contains(github.event.changes.body.from, '@github-actions approve me')))
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by an admin user?
        uses: sushichop/action-repository-permission@84a07d2aa5da31f9cee7dbd74216bce39ea6ae81
        with:
          required-permission: admin
          reaction-permitted: rocket
          comment-not-permitted:
            \"approve me\" アクションの発火には、Admin 以上の権限が必要です。
          comment-permitted: |
            Admin 以上の権限を持つユーザーの操作によって、Pull Request を approve します。
            :warning: このアクションの乱用は、デグレーデーションが発生しやすい状況を生み出してしまいます。
            可能であるかぎり、誰かに軽いレビューを依頼しましょう。
      - name: Approve pull request
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh pr review ${{ github.event.issue.number }} --approve
