name: build-and-test-workflow

on:
  schedule:
    - cron: '0 0 * * 0'
#  push:
#    branches:
#      - main
  #pull_request:

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache Npm packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

  test:
    name: Unit Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache Npm packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: npm run test

  approve:
    name: Approve
    steps:
      - name: Triggered by an admin user?
        uses: sushichop/action-repository-permission@84a07d2aa5da31f9cee7dbd74216bce39ea6ae81
        with:
          required-permission: admin
          reaction-permitted: rocket
          comment-not-permitted: \"approve me\" アクションの発火には、Admin 以上の権限が必要です。
          comment-permitted: |
            Admin 以上の権限を持つユーザーの操作によって、Pull Request を approve します。
            :warning: このアクションの乱用は、デグレーデーションが発生しやすい状況を生み出してしまいます。
            可能であるかぎり、誰かに軽いレビューを依頼しましょう。
      - name: Approve pull request
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh pr review ${{ github.event.issue.number }} --approve